name: "PR Workflow"

on:
  pull_request:

jobs:
  version:
    uses: ./.github/workflows/reusable/version.yaml
    secrets: inherit
    with:
      release-please: false

  build:
    needs: version
    uses: ./.github/workflows/reusable/dotnet.yaml
    with:
      dotnet-version: ${{ needs.version.outputs.dotnet-version }}
      void-version: ${{ needs.version.outputs.void-version }}
