using System.Text;
using Microsoft.CodeAnalysis;

namespace Void.IntegrationTests.Generators.Sources;

[Generator(LanguageNames.CSharp)]
public sealed class DirectConnectionReleaseGroupGenerator : ReleaseGroupGeneratorBase
{
    public override void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var generatedSourceProvider = context.CompilationProvider.Select(static (_, cancellationToken) => GenerateSource(cancellationToken));

        context.RegisterSourceOutput(generatedSourceProvider, static (sourceProductionContext, generatedSource) =>
        {
            if (generatedSource.Length is 0)
                return;

            sourceProductionContext.AddSource("DirectConnectionTests.g.cs", generatedSource);
        });
    }

    private static string GenerateSource(CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var generatedSourceBuilder = new StringBuilder();

        generatedSourceBuilder.AppendLine("// <auto-generated />");
        generatedSourceBuilder.AppendLine("#nullable enable");
        generatedSourceBuilder.AppendLine();
        generatedSourceBuilder.AppendLine("namespace Void.IntegrationTests.Connections.DirectConnectionTests;");
        generatedSourceBuilder.AppendLine();

        var groups = ReleaseVersionGroups.MajorMinor
            .OrderBy(group => group.Key)
            .Select(pair => (Key: pair.Key.ToString(), Releases: pair.Value.Select(release => release.ToString())))
            .Select(pair => (Key: pair.Key.Replace('.', '_'), Releases: pair.Releases.Select(release => release.Replace('.', '_'))));

        foreach (var (key, releases) in groups)
        {
            cancellationToken.ThrowIfCancellationRequested();

            generatedSourceBuilder.AppendLine($"public sealed class DirectConnectionTests_{key}(global::Void.IntegrationTests.Infrastructure.Fixtures.PaperFixture paperFixture, global::Void.IntegrationTests.Infrastructure.Fixtures.PortableMinecraftClientFixture portableMinecraftClientFixture) : DirectConnectionTestBase(paperFixture, portableMinecraftClientFixture)");
            generatedSourceBuilder.AppendLine("{");

            AppendTestMethodForReleases(generatedSourceBuilder, "PortableMinecraftClientConnectsToPaperServer_WithProtocolVersion", releases);

            generatedSourceBuilder.AppendLine("}");
            generatedSourceBuilder.AppendLine();
        }

        return generatedSourceBuilder.ToString();
    }
}
