<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Void.Client</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
  </ItemGroup>
</Project>
