name: Docker Publish
on:
  workflow_dispatch:
  workflow_run:
    workflows: [".NET Build"]
    types: ["completed"]

permissions:
  contents: write

jobs:
  publish-containers:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: latest
            os: ubuntu-latest
            args: '/p:ContainerRuntimeIdentifiers=''"linux-arm;linux-arm64;linux-x64"'' src/Platform'
          - name: latest-android
            os: ubuntu-latest
            args: '/p:ContainerImageTag=latest-android /p:ContainerRuntimeIdentifiers=''"linux-bionic-arm64;linux-bionic-x64"'' src/Platform'
          - name: latest-alpine
            os: ubuntu-latest
            args: '/p:ContainerImageTag=latest-alpine /p:ContainerRuntimeIdentifiers=''"linux-musl-arm;linux-musl-arm64;linux-musl-x64"'' src/Platform'
          - name: win-x64
            os: windows-latest
            args: '/p:ContainerImageTag=latest-windows /p:ContainerRuntimeIdentifier=win-x64 /p:ContainerBaseImage=mcr.microsoft.com/dotnet/runtime:9.0-nanoserver-ltsc2025 src/Platform'

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10'
          dotnet-quality: 'preview'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish ${{ matrix.name }}
        run: |
          dotnet publish /t:PublishContainer ${{ matrix.args }}