name: Docker Publish
on:
  workflow_dispatch:
  workflow_run:
    workflows: [".NET Build"]
    types: ["completed"]

permissions:
  contents: write

jobs:
  publish-containers:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            container_runtime_identifiers: linux-arm;linux-arm64;linux-x64
            container_image_tag: latest
          - os: ubuntu-latest
            container_runtime_identifiers: linux-bionic-arm64;linux-bionic-x64
            container_image_tag: latest-android
          - os: ubuntu-latest
            container_runtime_identifiers: linux-musl-arm;linux-musl-arm64;linux-musl-x64
            container_image_tag: latest-alpine
          - os: windows-latest
            container_runtime_identifiers: win-x64
            container_image_tag: latest-windows
            container_base_image: mcr.microsoft.com/dotnet/runtime:9.0-nanoserver-ltsc2025

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10'
          dotnet-quality: 'preview'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish ${{ matrix.container_image_tag }}
        run: |
          dotnet publish src/Platform \
            /t:PublishContainer \
            /p:ContainerRuntimeIdentifiers='"${{ matrix.container_runtime_identifiers }}"' \
            /p:ContainerImageTag="${{ matrix.container_image_tag }}" \
            /p:ContainerBaseImage="${{ matrix.container_base_image }}"