name: Google Indexing
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Google Indexing script
        run: npm i -g google-indexing-script
      - name: Index site
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          mkdir -p ~/.gis
          echo "$GCP_SA_KEY" > ~/.gis/service_account.json
          google-indexing-script void.caunt.world
