name: ".NET PR Workflow"

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/dotnet.yaml
    with:
      dotnet-version: '10.0.100-preview.6.25358.103'
      void-version: '0.0.0'
