name: ".NET PR Workflow"

on:
  pull_request:
    branches: ["main"]

jobs:
  semver:
    uses: ./.github/workflows/version.yaml
    secrets: inherit
    with:
      release-please: false

  build:
    needs: semver
    uses: ./.github/workflows/dotnet.yaml
    with:
      dotnet-version: ${{ needs.semver.outputs.dotnet-version }}
      void-version: ${{ needs.semver.outputs.void-version }}
