on:
  workflow_call:
    inputs:
      dotnet-version:
        type: string
        required: false
        default: 'latest'

permissions:
  pages: write
  id-token: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build DocFX
        run: docfx docs/docfx/docfx.json --verbose

      - name: Copy DocFX markdown into Astro pages
        run: mkdir -p docs/astro/src/reference && cp docs/docfx/reference/*.md docs/astro/src/reference/
        
      - name: Configure GitHub Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6

      - name: Install, build, and upload documentation site
        uses: withastro/action@b7d53628f8b666036b0238aadb0b984a2a489f26 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: docs/astro

#       - name: Validate links
#         uses: lycheeverse/lychee-action@v2
#         with:
#           args: --github-token ${{ secrets.GITHUB_TOKEN }} --base-url dist --exclude-all-private --exclude 404 --include-fragments dist
#           workingDirectory: docs/astro
#           lycheeVersion: nightly

      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
