name: "PR Workflow"

on:
  pull_request:

jobs:
  version:
    uses: ./.github/workflows/reusable-version.yml
    secrets: inherit
    with:
      release-please: false

  build:
    needs: version
    uses: ./.github/workflows/reusable-build.yml
    with:
      dotnet-version: ${{ needs.version.outputs.dotnet-version }}
      void-version: ${{ needs.version.outputs.void-version }}

  test:
    needs: version
    uses: ./.github/workflows/reusable-test.yml
    with:
      dotnet-version: ${{ needs.version.outputs.dotnet-version }}
      void-version: ${{ needs.version.outputs.void-version }}
